# Generated by Django 4.2.11 on 2025-04-07 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_student_cultural_event_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_cultural',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AddField(
            model_name='student_sports',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AddField(
            model_name='student_technical',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AlterField(
            model_name='student_sports',
            name='event_type',
            field=models.CharField(choices=[('national', 'National'), ('state', 'State'), ('district', 'District')], default='sports', max_length=20),
        ),
        migrations.AlterField(
            model_name='student_technical',
            name='event_type',
            field=models.CharField(choices=[('national', 'National'), ('state', 'State'), ('district', 'District')], default='technical', max_length=20),
        ),
    ]
